### ISSUE TITLE
there errors in the source lol 

### ISSUE THREAD

**Issue by imthecheeser** [channelRead0/raid0source#1]
can u fix the source? 
![image](https://github.com/user-attachments/assets/18f35047-9e1e-42a3-87d3-47be6f2a9dc0)
![image](https://github.com/user-attachments/assets/46da81ce-3929-4da9-9930-7a4d1c254488)
![image](https://github.com/user-attachments/assets/e26a0590-ac4d-4662-a8de-6048a159bb3e)
![image](https://github.com/user-attachments/assets/3ffbeb86-760c-48f4-9dc4-130728d876c3)

**Comment by nevarlackin** [comment]
Add them urself lazy skidder

**Comment by imthecheeser** [comment]
> Add them urself lazy skidder

xD
